# -*- coding: utf-8 -*-
"""Browse trough the internet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ghaJzuCMbPlTURMtPZkGRlOSCqGsW7yp

Browse trough the internet
"""

#1. Entrar na internet
import panda as pd
from selenium import webdriver
navegador = webdriver.Chrome()
#selenium normalmente espera o site carregar, não precisa pedir segundos como time.sleep 

#2. Pegar cotação dólar
navegador.get('https://www.google.com.br/')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação dolar')		#procura o elemento da página para ser mais especifico
##clicar com botão direito do mouse > inspecionar > 1 botão da aba que abrir que tem um quadrado e uma seta e clicar > passar o mouse na pagina para achar o que queremos, clicar, vai aparecer o que queremos, copiar o codigo que aparece e cola no código acima
## o send_keys é para dizer o que queremos digitar naquele path. 
## Ou seja, podemos abrir o google e pesquisar algo na internet
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('Keys.ENTER')			#Da enter no site para rodar a busca

cotacao_dolar= navegador.find_element_by_xpath('').get_attribute('data-value')	#colocar o xpath do que queremos, no caso, o valor do $ (data-value, ta escrito no xpath dele)
print(cotacao_dolar)

#3. Pegar cotação euro
navegador.get('https://www.google.com.br/')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('cotação euro')
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys('Keys.ENTER')
			
cotacao_euro= navegador.find_element_by_xpath('').get_attribute('data-value')	
print(cotacao_euro)

#4. Pegar cotação ouro
navegador.get('https://www.melhorcambio.com/ouro-hoje')
navegador.find_element_by_xpath('//*[@id="comercial"]').get.attribute('value')
print(cotacao_euro)

#5. Fechar aba
navegador.quit()

#6. Importar e atualziar a base de dados
tabela = pd.read_excel('')
display(tabela)

##atualizar cotação
###tabela.loc[tabela["coluna_referencia"] == linha_ref, coluna_alterar]
tabela.loc[tabela["Moeda"] == 'Dólar', 'Cotação'] = float(cotacao_dolar)
tabela.loc[tabela["Moeda"] == 'Dólar', 'Cotação'] = float(cotacao_euro)
tabela.loc[tabela["Moeda"] == 'Dólar', 'Cotação'] = float(cotacao_ouro)
display(tabela)

##atualizar Preço de Compra > Preço original*cotação
tabela['Preço de Compra'] = tabela['Preço Original'] * tabela ['Cotação']
display(tabela)

##atualizar Preço de vende > preço de compra*margem
tabela['Preço de Vende'] = tabela['Preço Compra'] * tabela ['Margem']
display(tabela)

#7. Exportar a base de dados atualizada
tabela.to_excel('.xlsx')